/**
 * Animation Metadata
 * Central metadata for all registered animations
 */

import type { AnimationMetadata } from '../../types/animation'

export const animationMetadata: AnimationMetadata[] = [
  {
    id: 'particle-burst',
    name: 'Particle Burst',
    description: 'Explosive particle system with colorful bursts radiating from random points',
    category: 'particles',
    difficulty: 'easy',
    tags: ['particles', 'explosion', 'colorful', 'physics'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
    parameters: [
      {
        name: 'particleCount',
        label: 'Particle Count',
        type: 'number',
        defaultValue: 40,
        min: 10,
        max: 100,
        step: 5,
        description: 'Number of particles per burst',
      },
      {
        name: 'particleSpeed',
        label: 'Particle Speed',
        type: 'number',
        defaultValue: 3,
        min: 1,
        max: 10,
        step: 0.5,
        description: 'Velocity of particle emission',
      },
      {
        name: 'particleSize',
        label: 'Particle Size',
        type: 'number',
        defaultValue: 3,
        min: 1,
        max: 8,
        step: 0.5,
        description: 'Base size of particles',
      },
      {
        name: 'gravity',
        label: 'Gravity',
        type: 'number',
        defaultValue: 0.15,
        min: 0,
        max: 1,
        step: 0.05,
        description: 'Downward force applied to particles',
      },
      {
        name: 'spawnRate',
        label: 'Spawn Rate (ms)',
        type: 'number',
        defaultValue: 50,
        min: 10,
        max: 500,
        step: 10,
        description: 'Time between bursts in milliseconds',
      },
      {
        name: 'primaryColor',
        label: 'Primary Color',
        type: 'color',
        defaultValue: '#ff6b6b',
        description: 'Main color of particles',
      },
      {
        name: 'showTrails',
        label: 'Show Trails',
        type: 'boolean',
        defaultValue: true,
        description: 'Enable motion trail effect',
      },
    ],
  },
  {
    id: 'particle-wave',
    name: 'Particle Wave',
    description: 'Particles arranged in flowing wave formations with smooth motion',
    category: 'particles',
    difficulty: 'easy',
    tags: ['particles', 'wave', 'flow', 'smooth'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'constellation',
    name: 'Constellation',
    description: 'Connected particle network forming constellation patterns',
    category: 'particles',
    difficulty: 'medium',
    tags: ['particles', 'network', 'connected', 'stars'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'fireflies',
    name: 'Fireflies',
    description: 'Glowing particles floating with pulsing brightness',
    category: 'particles',
    difficulty: 'easy',
    tags: ['particles', 'glow', 'organic', 'nature'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'explosion',
    name: 'Explosion',
    description: 'Continuous explosions with particle debris and gravity',
    category: 'particles',
    difficulty: 'medium',
    tags: ['particles', 'explosion', 'physics', 'dynamic'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'gravity-field',
    name: 'Gravity Field',
    description: 'Particles attracted to moving gravity wells',
    category: 'particles',
    difficulty: 'hard',
    tags: ['particles', 'physics', 'gravity', 'attraction'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'dna-helix',
    name: 'DNA Helix',
    description: 'Double helix structure made of rotating particles',
    category: 'particles',
    difficulty: 'hard',
    tags: ['particles', '3d', 'biology', 'structure'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'starfield',
    name: 'Starfield',
    description: 'Moving star field with parallax depth effect',
    category: 'particles',
    difficulty: 'medium',
    tags: ['particles', '3d', 'space', 'parallax'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'sine-wave',
    name: 'Sine Wave',
    description: 'Flowing multi-colored sine waves with smooth glow effects',
    category: 'waves',
    difficulty: 'easy',
    tags: ['waves', 'flow', 'colorful', 'smooth'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'wave-interference',
    name: 'Wave Interference',
    description: 'Multiple wave sources creating complex interference patterns',
    category: 'waves',
    difficulty: 'medium',
    tags: ['waves', 'physics', 'interference', 'pattern'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'audio-visualizer',
    name: 'Audio Visualizer',
    description: 'Simulated audio spectrum with frequency bars and peaks',
    category: 'waves',
    difficulty: 'medium',
    tags: ['waves', 'audio', 'spectrum', 'music'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'liquid-morph',
    name: 'Liquid Morph',
    description: 'Organic morphing blob using metaball technique',
    category: 'waves',
    difficulty: 'hard',
    tags: ['waves', 'organic', 'metaballs', 'fluid'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'line-waves',
    name: 'Line Waves',
    description: 'Flowing lines creating layered wave patterns',
    category: 'waves',
    difficulty: 'easy',
    tags: ['waves', 'lines', 'flow', 'layered'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'glitch-text',
    name: 'Glitch Text',
    description: 'Cyberpunk-style text glitching with RGB color separation and scan lines',
    category: 'glitch',
    difficulty: 'medium',
    tags: ['glitch', 'text', 'cyberpunk', 'rgb', 'retro'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'rotating-cubes',
    name: 'Rotating Cubes',
    description: '3D rotating cubes with perspective projection',
    category: 'geometric',
    difficulty: 'hard',
    tags: ['3d', 'cubes', 'rotation', 'perspective', 'geometry'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'polygon-morph',
    name: 'Polygon Morph',
    description: 'Morphing between different polygon shapes',
    category: 'geometric',
    difficulty: 'medium',
    tags: ['polygons', 'morph', 'shapes', 'animation', 'geometry'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'grid-distortion',
    name: 'Grid Distortion',
    description: 'Distorted grid with wave effects',
    category: 'geometric',
    difficulty: 'medium',
    tags: ['grid', 'distortion', 'waves', 'mesh', 'geometry'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'hexagon-grid',
    name: 'Hexagon Grid',
    description: 'Pulsing hexagonal grid pattern',
    category: 'geometric',
    difficulty: 'medium',
    tags: ['hexagons', 'grid', 'pulse', 'pattern', 'geometry'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'sacred-geometry',
    name: 'Sacred Geometry',
    description: 'Rotating sacred geometry patterns',
    category: 'geometric',
    difficulty: 'medium',
    tags: ['sacred', 'geometry', 'rotation', 'mandala', 'patterns'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'matrix-rain',
    name: 'Matrix Rain',
    description: 'Falling matrix-style characters with glowing trails',
    category: 'text',
    difficulty: 'medium',
    tags: ['matrix', 'text', 'rain', 'terminal', 'cyberpunk'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'type-effect',
    name: 'Type Effect',
    description: 'Typewriter effect with cursor and text reveal',
    category: 'text',
    difficulty: 'easy',
    tags: ['typewriter', 'text', 'cursor', 'terminal', 'animation'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'rgb-split',
    name: 'RGB Split',
    description: 'RGB channel separation glitch effect',
    category: 'glitch',
    difficulty: 'hard',
    tags: ['glitch', 'rgb', 'chromatic', 'aberration', 'effect'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'scan-lines',
    name: 'Scan Lines',
    description: 'CRT scanline effect with glitch artifacts',
    category: 'glitch',
    difficulty: 'medium',
    tags: ['scanlines', 'crt', 'glitch', 'retro', 'vhs'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
  {
    id: 'pixel-sort',
    name: 'Pixel Sort',
    description: 'Pixel sorting glitch effect with directional sorting',
    category: 'glitch',
    difficulty: 'hard',
    tags: ['pixel', 'sort', 'glitch', 'distortion', 'art'],
    author: 'Animation Specialist',
    createdAt: '2025-12-07',
    updatedAt: '2025-12-07',
  },
]
